language: c

sudo: false

env:
  global:
    - LUAROCKS=2.4.1
  matrix:
    - LUA=lua5.3
    - LUA=luajit
    - LUA=luajit SERVER=openresty

before_install:
  - source .travis/setenv_lua.sh
install:
    - luarocks install middleclass
    - luarocks install lua-requests
    - luarocks install busted

script:
  - busted spec/*

notifications:
  email:
    on_success: change
    on_failure: always
