local API = require('api')
local class = require('middleclass')

local api = API()
local account = require('account')

local json = require('json')

describe('account()', function()

  describe('when getting the balance', function()
      it('should give us the balance', function()
          resp = account:get_balance("AWVeBC3Czop9YcVUoegzdaNyvXs3vUcsze")
          local toJson = json.decode(resp)
          assert.same(toJson["success"], true)
      end)
  end)
  
  describe('when getting the public key', function()
      it('should give us the public key of an account', function()
          resp = account:get_public_key("AWVeBC3Czop9YcVUoegzdaNyvXs3vUcsze")
          local toJson = json.decode(resp)
          assert.same(toJson["success"], true)
      end)
  end)

  describe('when getting delegate fee', function()
      it('should give us the delegate fee of an account', function()
          resp = account:get_delegate_fee()
          local toJson = json.decode(resp)
          assert.same(toJson["success"], true)
      end)
  end)

  describe('when getting the delegates', function()
      it('should give us the delegates of an account', function()
          resp = account:get_delegates("AWVeBC3Czop9YcVUoegzdaNyvXs3vUcsze")
          local toJson = json.decode(resp)
          assert.same(toJson["success"], true)
      end)
  end)

  describe('when getting the account information', function()
      it('should give us the account informations of an address', function()
          resp = account:get_accounts("AWVeBC3Czop9YcVUoegzdaNyvXs3vUcsze")
          local toJson = json.decode(resp)
          assert.same(toJson["success"], true)
      end)
  end)

  describe('when getting the top accounts', function()
      it('should give us a list of the top accounts', function()
          resp = account:get_top_accounts()
          local toJson = json.decode(resp)
          assert.same(toJson["success"], true)
      end)
  end)
end)