local API = require('api')
local class = require('middleclass')

local api = API()
local block = require('block')

local json = require('json')

describe('block()', function()

  describe('when getting a block by his id', function()
      it('should give us the block informations', function()
          resp = block:get_block("570934191207974498")
          local toJson = json.decode(resp)
          assert.same(toJson["success"], true)
      end)
  end)

    describe('when getting all blocks', function()
        it('should give us the blocks informations', function()
            resp = block:get_blocks()
            local toJson = json.decode(resp)
            assert.same(toJson["success"], true)
        end)
    end)

    describe('when getting the height', function()
        it('should give us the blockchain height', function()
            resp = block:get_height()
            local toJson = json.decode(resp)
            assert.same(toJson["success"], true)
        end)
    end)

    describe('when getting the nethash', function()
        it('should give us the blockchain nethash', function()
            resp = block:get_nethash()
            local toJson = json.decode(resp)
            assert.same(toJson["success"], true)
        end)
    end)

    describe('when getting the fee', function()
        it('should give us the blockchain fee', function()
            resp = block:get_fee()
            local toJson = json.decode(resp)
            assert.same(toJson["success"], true)
        end)
    end)

    describe('when getting the network fees', function()
        it('should give us the network fees', function()
            resp = block:get_fees()
            local toJson = json.decode(resp)
            assert.same(toJson["success"], true)
        end)
    end)

    describe('when getting the milestone', function()
        it('should give us the blockchain milestone', function()
            resp = block:get_milestone()
            local toJson = json.decode(resp)
            assert.same(toJson["success"], true)
        end)
    end)

    describe('when getting the reward', function()
        it('should give us the blockchain reward', function()
            resp = block:get_reward()
            local toJson = json.decode(resp)
            assert.same(toJson["success"], true)
        end)
    end)

    describe('when getting the supply', function()
        it('should give us the blockchain supply', function()
            resp = block:get_supply()
            local toJson = json.decode(resp)
            assert.same(toJson["success"], true)
        end)
    end)

    describe('when getting the status', function()
        it('should give us the blockchain status', function()
            resp = block:get_status()
            local toJson = json.decode(resp)
            assert.same(toJson["success"], true)
        end)
    end)
end)
